on:
  push:
    branches:
      - master
      - main

jobs:
  Musl-Build:
    runs-on: alpine-latest

    steps:
        - name: ^ Checkout
          uses: actions/checkout@v2
        
        - name: Create build dir.
          run: sudo mkdir /source
        
        - name: Copy data.
          run: sudo cp -r * /source/

        - name: Run Init.
          run: cd /source && sudo sh init.sh
        
        - name: Collect Artifacts.
          run: sudo mkdir /artifacts && sudo cp /runner/page/{ticlock,ticlock-x86_64.AppImage} /artifacts/

        - name: Upload Artifacts.
          uses: actions/upload-artifact@v2
          with:
            name: binaries
            path: /artifacts

