on:
  push:
    branches:
      - master
      - main

jobs:
  Musl-Build:
    runs-on: ubuntu-latest

    container: alpine

    steps:
        - name: ^ Checkout
          uses: actions/checkout@v2
        
        - name: Create build dir.
          run: mkdir /source
        
        - name: Copy data.
          run: cp -r * /source/

        - name: Download tar.gz AppImage.
          run: wget https://gameplayer.xaviama.dank-me.me/shared/appimagetool.tar.gz -O /opt/tool.tar.gz
        
        - name: Install tar.
          run: apk add --no-cache tar
        
        - name: Extract tools.
          run: cd /opt && tar -xvf tool.tar.gz && mv /opt/squashfs-root /opt/appimagetool.AppDir

        - name: Run Init.
          run: cd /source && sh init.sh
        
        - name: Collect Artifacts.
          run: mkdir -p /artifacts/{AppImage,Binary} && cp /runner/page/ticlock-x86_64.AppImage /artifacts/AppImage/ && cp /runner/page/ticlock /artifacts/Binary/

        - name: Upload AppImage.
          uses: actions/upload-artifact@v2
          with:
            name: AppImage
            path: /artifacts/AppImage
        
        - name: Upload Binary.
          uses: actions/upload-artifact@v2
          with:
            name: Binary
            path: /artifacts/Binary

