on:
  push:
    branches:
      - master
      - main

jobs:
  Musl-Build:
    runs-on: ubuntu-latest

    steps:
        - uses: jirutka/setup-alpine@v1
          with:
            branch: v3.15
        
        - name: ^ Checkout
          uses: actions/checkout@v2
        
        - name: Create build dir.
          run: sudo mkdir /source
        
        - name: Copy data.
          run: sudo cp -r * /source/

        - name: Run Init.
          run: cd /source && sudo sh init.sh
        
        - name: Collect Artifacts.
          run: sudo mkdir -p /artifacts/{AppImage,Binary} && sudo cp /runner/page/ticlock-glibc-x86_64.AppImage /artifacts/AppImage/ && sudo cp /runner/page/ticlock-glibc /artifacts/Binary/

        - name: Upload AppImage.
          uses: actions/upload-artifact@v2
          with:
            name: AppImage
            path: /artifacts/AppImage
        
        - name: Upload Binary.
          uses: actions/upload-artifact@v2
          with:
            name: Binary
            path: /artifacts/Binary

